name: Documentation
description: Report incorrect, missing, or unclear documentation
labels: ["docs"]
body:
  - type: markdown
    attributes:
      value: |
        Help us improve the docs.

  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - Missing documentation
        - Incorrect documentation
        - Unclear / confusing
        - Typo
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What's wrong or missing? Link to the relevant section if possible.
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggested Fix
      description: If you have a fix in mind, describe it here.