name: Feature Request
description: Suggest a new feature or endpoint
labels: ["feature"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea for a new feature? We'd love to hear it.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What's the use case?
      placeholder: I need to fetch a user's reading log, but there's no endpoint for it...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How do you think this should work? Include example API if possible.
      render: ts
      placeholder: |
        const log = await ol.myBooks.get("username", "want-to-read");
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any workarounds or alternative approaches you've thought of.

  - type: dropdown
    id: scope
    attributes:
      label: Scope
      description: What area does this affect?
      options:
        - New endpoint
        - Existing endpoint improvement
        - Client configuration
        - Types / Schemas
        - Developer experience
        - Other
    validations:
      required: true